--require('base16-colorscheme').setup({
--    base00 = "#111418",
--    base01 = "#0b0e13",
--    base02 = "#191c20",
--    base03 = "#43474e",
--    base04 = "#c3c6cf",
--    base05 = "#e1e2e8",
--    base06 = "#2e3135",
--    base07 = "#36393e",
--    base08 = "#ccacdd",
--    base09 = "#d7bee4",
--    base0A = "#bbc7db",
--    base0B = "#a1cafd",
--    base0C = "#533f5f",
--    base0D = "#1b4975",
--    base0E = "#3c4858",
--    base0F = "#9aacc9",
--})
-- Generated by Matugen

require("base16-colorscheme").setup({
	base00 = "#111418",
	base01 = "#0b0e13",
	base02 = "#191c20",
	base03 = "#43474e",
	base04 = "#c3c6cf",
	base05 = "#e1e2e8",
	base06 = "#2e3135",
	base07 = "#36393e",

	base08 = "#ccacdd",
	base09 = "#d7bee4",
	base0A = "#bbc7db",
	base0B = "#a1cafd",
	base0C = "#533f5f",
	base0D = "#1b4975",
	base0E = "#3c4858",
	base0F = "#9aacc9",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#1b4975",
	fg = "#d2e4ff", -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ "String", "TSString" }, {
	fg = "#b688ce",
})

-- Grey out comments
set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "#8d9199",
	italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "#d7bee4",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "#bbc7db",
})

set_hl_mutliple({ "Keyword", "TSKeyword", "TSKeywordFunction", "TSRepeat" }, {
	fg = "#37618e",
})
